#version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    ports:
      - "3001:3000"
